### PR TITLE
[NO-1748] Remove sensitive data from Pubsub loggers

### PR DESCRIPTION
**Pull request by Bendakh**
## Description

Through this PR, we removed some sensitive data from the pubsub loggers.

### CODE REVIEW

**Review by g-ongenae — APPROVED** [review]

**Review by qhdinh — COMMENTED** [review]
I thought we only wanted to hide the sensitive data in the payload. Here we log 0 data in the PusSub payload, so how to debug?

**Comment by qhdinh** [comment]
There is also `data` at the end of `emit()`?
```
return topic.publishMessage({
      json: data,
      attributes: { ...attributes, ...opts.metadata },
      ...opts.options?.messageOptions,
    });
```

**Comment by Bendakh** [comment]
> I thought we only wanted to hide the sensitive data in the payload. Here we log 0 data in the PusSub payload, so how to debug?

In the investigation I saw that we want to remove the data and payloads

**Review by qhdinh — APPROVED** [review]

**Review by amarlankri — APPROVED** [review]
Thanks @Bendakh!

**Pull request merged**
